### ISSUE TITLE
Xbox wiresless controller connected over usb was detected but stopped being detected after updating firmware

### ISSUE THREAD

**Issue by Xii-Nyth** [bwRavencl/ControllerBuddy#88]
I restarted, delteted contents in appdata/local/temp, and re unpacked the rogram files form the 7z

Curiously it also somehow remembers the dark mode setting?
Is there a config file somewhere im missing that I should try deleting?

**Comment by bwRavencl** [comment]
Hi @Xii-Nyth,

#### First of all a few questions:
1. Which exact version of ControllerBuddy are you using?
2. Have you tried with the latest release [ControllerBuddy-0.25.61-0820961](https://github.com/bwRavencl/ControllerBuddy/releases/tag/ControllerBuddy-0.25.61-0820961)?
3. Does your Xbox controller work with other applications / games?

#### Some technical background:
ControllerBuddy uses a library called LWJGL which in turn is based on another library called GLFW. ControllerBuddy asks these librarys which gamepads are present and then, continually polls the gamepads to receive their current state (i.e. state of the axes and if buttons are pressed or not).  
On your system it seems that GLFW fails to detect your Xbox Controller. 
GLFW uses a database called [SDL_GameControllerDB](https://github.com/gabomdq/SDL_GameControllerDB) which contains entries on a vast majority of the different makes and models of gamepads that exist.
It is this point where we should start and ensure that there is a database entry for your specific kind of Xbox controller.  
If what you are using is a standard, official Microsoft Xbox controller it is somewhat surprising to me that a database entry could be missing for it, however let’s validate that:  

There is a tool called [SDL2 Gamepad Tool](https://www.generalarcade.com/gamepadtool/) which can be used to check if a gamepad is found in the database and if not helps you to create a database entry for it.
It would be very helpful if you could download and run said tool and then report back to me with a screenshot of the output and also include the so called GUID of your gamepad. This is a unique identifier for a specific gamepad model that is used to reference database entries. If the GUID of your gamepad is not present in the database this would explain why your gamepad is not detected. We could simply create an entry and mapping for your model and provide it to the folks of SDL_GameControllerDB. Afterwards I would create a new build of ControllerBuddy that uses the latest version of the database and your controller should be detected.

I currently suspect that the firmware update of your controller somehow changed the parameters of your controller from which the GUID is derived and can now no longer be found in the database.

There was an update to the database on the 27th of February regarding an Xbox Series controllers firmware update: https://github.com/gabomdq/SDL_GameControllerDB/commit/9daf08ce77c7a96b2f9935f4e325efbbc60a8b93
I have already updated the database shipped with ControllerBuddy-0.25.26-80873a6 - that's why I am asking for you to try with the latest release, which includes said update and more fixes / improvements.

#### Finally, regarding your question about a config file:
There is no config file for ControllerBuddy, all the settings are stored in the Windows registry.
However, there is no need for you to delete anything from there, it is not going to fix your specific issue. ;-)

Cheers and good luck,
Matteo

**Comment by bwRavencl** [comment]
Closing this issue as it does not seem to be a bug in ControllerBuddy and the submitter has not responded anymore.

The described problem is not reproducible with ControllerBuddy 0.25.142-b4a53bf on my end.
The hardware used was an Xbox Series X|S controller, updated to the latest firmware, and connected via USB on Windows 11.
